backend:
  build: ./backend
  ports:
    - "8888:8888"
  volumes:
    - ./backend:/backend
    - ./contracts:/contracts
  command: bash -c "python manage.py db upgrade && python manage.py runserver -h 0.0.0.0 -p 8888"
  links:
    - node
    - db

node:
  image: trufflesuite/ganache-cli
  ports:
    - "8545:8545"
  volumes:
    - ./.ethereum_data:/ethereum_data
  entrypoint:
    - node
    - ./build/cli.node.js
    - -n
    - -a
    - '10'
    - --db=/ethereum_data

db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

web:
  image: nginx
  volumes:
   - ./frontend/ethereum-frontend.conf:/etc/nginx/conf.d/default.conf
   - ./frontend/vote:/var/www/ethereum
  links:
   - backend
   - frontend
  ports:
   - "8080:80"

frontend:
  image: "node:8"
  working_dir: /home/node/app
  volumes:
    - ./frontend/vote:/home/node/app
  expose:
    - "8080"
  command: bash -c "npm install && npm start"