backend:
  build: ./backend
  ports:
    - "8888:8888"
  volumes:
    - ./backend:/backend
    - ./contracts:/contracts
  command: python manage.py runserver -h 0.0.0.0 -p 8888
  links:
    - node
    - db

node:
  image: trufflesuite/ganache-cli
  ports:
    - "8545:8545"
  entrypoint:
    - node
    - ./build/cli.node.js
    - -n
    - -a
    - '10'

db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

web:
  image: nginx
  volumes:
   - ./frontend/ethereum-frontend.conf:/etc/nginx/conf.d/default.conf
   - ./frontend/vote:/var/www/ethereum
  links:
   - backend
  ports:
   - "8080:80"